# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='sample',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csample.proto\x12\x06sample\" \n\rSampleRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0eSampleResponse\x12\r\n\x05reply\x18\x01 \x01(\t2H\n\rSampleService\x12\x37\n\x04\x43\x61ll\x12\x15.sample.SampleRequest\x1a\x16.sample.SampleResponse\"\x00\x62\x06proto3'
)




_SAMPLEREQUEST = _descriptor.Descriptor(
  name='SampleRequest',
  full_name='sample.SampleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='sample.SampleRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=56,
)


_SAMPLERESPONSE = _descriptor.Descriptor(
  name='SampleResponse',
  full_name='sample.SampleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='sample.SampleResponse.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['SampleRequest'] = _SAMPLEREQUEST
DESCRIPTOR.message_types_by_name['SampleResponse'] = _SAMPLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SampleRequest = _reflection.GeneratedProtocolMessageType('SampleRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEREQUEST,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.SampleRequest)
  })
_sym_db.RegisterMessage(SampleRequest)

SampleResponse = _reflection.GeneratedProtocolMessageType('SampleResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLERESPONSE,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.SampleResponse)
  })
_sym_db.RegisterMessage(SampleResponse)



_SAMPLESERVICE = _descriptor.ServiceDescriptor(
  name='SampleService',
  full_name='sample.SampleService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=91,
  serialized_end=163,
  methods=[
  _descriptor.MethodDescriptor(
    name='Call',
    full_name='sample.SampleService.Call',
    index=0,
    containing_service=None,
    input_type=_SAMPLEREQUEST,
    output_type=_SAMPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAMPLESERVICE)

DESCRIPTOR.services_by_name['SampleService'] = _SAMPLESERVICE

# @@protoc_insertion_point(module_scope)
