/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;

import sample.Sample.SampleRequest;
import sample.Sample.SampleResponse;
import sample.SampleServiceGrpc;

public class SampleClient {
    public static void main(String[] args) {
        final int portNumber = 9999;
        ManagedChannel channel = ManagedChannelBuilder.forAddress("localhost", portNumber)
                                .usePlaintext().build();
        SampleServiceGrpc.SampleServiceBlockingStub stub
                 = SampleServiceGrpc.newBlockingStub(channel);

        SampleRequest request = SampleRequest.newBuilder()
                                .setMessage("test message (java)").build();
        
        System.out.println("request : " + request.getMessage());
        SampleResponse response = stub.call(request);
        System.out.println("response : " + response.getReply());
    }
}
